services:
  # MongoDB Database
  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - todo-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # Mongo Express Admin UI
  mongo-express:
    image: mongo-express:latest
    container_name: todo-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    networks:
      - todo-network
    depends_on:
      mongodb:
        condition: service_healthy

  # Todo WebApp
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    container_name: todo-webapp
    ports:
      - "8080:8080"
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: "27017"
      MONGODB_DATABASE: ToDoAppDb
    networks:
      - todo-network
    depends_on:
      mongodb:
        condition: service_healthy

# Named volume for MongoDB data persistence
volumes:
  mongodb-data:

# Custom network for container communication
networks:
  todo-network:
    driver: bridge